// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/__username__/go_boilerplate/internal/config"

func HeaderCore(site config.Site) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"sticky top-0 z-50 bg-primary/95 backdrop-blur-md text-std shadow-lg border-b border-accent/20\" hx-boost=\"true\" x-data=\"{ mobileMenuOpen: false }\"><div class=\"container mx-auto px-4 lg:px-6\"><div class=\"flex items-center justify-between h-16\" x-data=\"{\n\t\t\t\t\t\t\tmobileMenuOpen: false,\n\t\t\t\t\t\t\tdarkMode: localStorage.getItem(&#39;darkMode&#39;) === &#39;true&#39; ? true :\n\t\t\t\t\t\t\t\t\t(localStorage.getItem(&#39;darkMode&#39;) === &#39;false&#39; ? false :\n\t\t\t\t\t\t\t\t\twindow.matchMedia(&#39;(prefers-color-scheme: dark)&#39;).matches)\n  \t\t\t\t\t\t}\" x-init=\"\n\t\t\t\t\tif(darkMode) {\n\t\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\n\t\t\t\t\t} else {\n\t\t\t\t\t\tdocument.documentElement.classList.remove(&#39;dark&#39;);\n\t\t\t\t\t}\n\n\t\t\t\t\t$watch(&#39;darkMode&#39;, val =&gt; {\n\t\t\t\t\t\tlocalStorage.setItem(&#39;darkMode&#39;, val);\n\t\t\t\t\t\tif(val) {\n\t\t\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\n\t\t\t\t\t\t} else {\n\t\t\t\t\t\t\tdocument.documentElement.classList.remove(&#39;dark&#39;);\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\n\n\t\t\t\t\twindow.matchMedia(&#39;(prefers-color-scheme: dark)&#39;).addEventListener(&#39;change&#39;, e =&gt; {\n\t\t\t\t\t\tif (localStorage.getItem(&#39;darkMode&#39;) === null) {\n\t\t\t\t\t\t\tdarkMode = e.matches;\n\t\t\t\t\t\t}\n\t\t\t\t\t\t});\n\t\t\t\t\t\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
