services:
  go_boilerplatedb:
    container_name: go_boilerplatedb
    image: postgres:15.3-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U __username__ -d go_boilerplatedb"]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - traefik.enable=false
    networks:
      - go_boilerplatenet
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5467:5432"
    volumes:
      - go_boilerplatepgdata:/var/lib/postgresql/data
      - go_boilerplatepgconf:/etc/postgresql
      - go_boilerplatepglog:/var/log/postgresql
  go_boilerplate:
    container_name: go_boilerplate
    image: go_boilerplate
    restart: unless-stopped
    depends_on:
      go_boilerplatedb:
        condition: service_healthy
    environment:
      - GO_ENV
      - HOST
      - PORT
      - DSN
      - NTFY
      - METRICS_SECRET
      - PROMETHEUS
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:__port__/healthcheck"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.go_boilerplate.rule=Host(`go_boilerplate.example.com`)
      - traefik.http.routers.go_boilerplate.entrypoints=web,websecure
      - traefik.http.routers.go_boilerplate.service=go_boilerplate
      - traefik.http.services.go_boilerplate.loadbalancer.server.port=__port__
      - traefik.http.routers.go_boilerplate.tls=true
      - traefik.http.routers.go_boilerplate.tls.certresolver=letsencrypt
      - traefik.http.routers.go_boilerplate.middlewares=websocket-headers,forwardedheaders
    networks:
      - go_boilerplatenet
      - proxy
      - monitoring
    ports:
      - __port__:__port__

networks:
  proxy:
    external: true
  monitoring:
    external: true
  go_boilerplatenet:
    driver: bridge
    external: false

volumes:
  go_boilerplatepgdata:
    driver: local
  go_boilerplatepgconf:
    driver: local
  go_boilerplatepglog:
    driver: local
